name: Keep Streamlit Apps Awake

on:
  schedule:
    - cron: "0 */8 * * *"   # every 8 hours
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Video Translator
        run: curl -I https://video-player-1.streamlit.app/

      
