name: Redeploy Multiple Streamlit Apps

on:
  workflow_dispatch:   # Manual trigger from GitHub UI
  schedule:
    - cron: "0 3 * * *"   # Every day at 3AM UTC

jobs:
  redeploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app_repo: [
          
          
          "tusharkamthe23video-player",
          "tusharkamthe23dynamic-ai-agent-with-web-search-frontend",
          #"":Tusharkamthe23Crop-recommendation-system"
          "Tusharkamthe23Video-Ai-Agent",
          "Tusharkamthe23Video-translator",
          "Tusharkamthe23tusharkamthe23chatbot"
        ]

    steps:
      - name: Checkout central repo
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"

      - name: Trigger Redeploy for ${{ matrix.app_repo }}
        run: |
          repo_url="https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/${{ matrix.app_repo }}.git"

          echo "Cloning $repo_url"
          git clone "$repo_url" app
          cd app

          git commit --allow-empty -m "Trigger Streamlit rebuild $(date)"
          git push "$repo_url" HEAD:main
